# Nombre del flujo de trabajo
name: CI básico - Instalar dependencias

# Evento que dispara este workflow: cada vez que haya un push en la rama main
on:
  push:
    branches:
      - main

# Definición de trabajos que se ejecutarán
jobs:
  install-dependencies:
    # Tipo de máquina virtual donde correrá el job (Ubuntu es común y gratuito)
    runs-on: ubuntu-latest

    # Pasos que se ejecutan en este job
    steps:
      # Paso 1: Clonar el repositorio para tener el código
      - name: Checkout del código
        uses: actions/checkout@v3

      # Paso 2: Configurar Node.js con la versión que uses (ejemplo: 18)
      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Paso 3: Instalar las dependencias definidas en package.json usando npm
      - name: Instalar dependencias npm
        run: npm install

      # Paso 4: (Opcional) Ejecutar tests si tienes definidos en package.json
      - name: Ejecutar tests
        run: npm test
